apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
  - port: 80
    name: web
    targetPort: 8000
    protocol: TCP
  - port: 443
    name: websecure
    targetPort: 8443
    protocol: TCP